// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package query

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAuthor = `-- name: CreateAuthor :exec
INSERT INTO authors (id, name, bio) VALUES ($1, $2, $3)
`

type CreateAuthorParams struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.exec(ctx, q.createAuthorStmt, createAuthor, arg.ID, arg.Name, arg.Bio)
	return err
}

const createAuthors = `-- name: CreateAuthors :exec
INSERT INTO authors
SELECT unnest($1::BIGINT[]) AS id,
  unnest($2::TEXT[]) AS name,
  unnest($3::TEXT_NULL[]) AS bio
`

type CreateAuthorsParams struct {
	IDs   []int64
	Names []string
	Bios  []sql.NullString
}

func (q *Queries) CreateAuthors(ctx context.Context, arg CreateAuthorsParams) error {
	_, err := q.exec(ctx, q.createAuthorsStmt, createAuthors, pq.Array(arg.IDs), pq.Array(arg.Names), pq.Array(arg.Bios))
	return err
}

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors SET name = $2, bio = $3 WHERE id = $1
`

type UpdateAuthorParams struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	_, err := q.exec(ctx, q.updateAuthorStmt, updateAuthor, arg.ID, arg.Name, arg.Bio)
	return err
}

const updateAuthors = `-- name: UpdateAuthors :exec
UPDATE authors AS a
SET name = tmp.name, bio = tmp.bio
FROM (
  SELECT unnest($1::BIGINT[]) AS id,
  unnest($2::TEXT[]) AS name,
  unnest($3::TEXT_NULL[]) AS bio
) AS tmp
WHERE a.id = tmp.id
`

type UpdateAuthorsParams struct {
	IDs   []int64
	Names []string
	Bios  []sql.NullString
}

func (q *Queries) UpdateAuthors(ctx context.Context, arg UpdateAuthorsParams) error {
	_, err := q.exec(ctx, q.updateAuthorsStmt, updateAuthors, pq.Array(arg.IDs), pq.Array(arg.Names), pq.Array(arg.Bios))
	return err
}
